CREATE TABLE `events` (
	`id` int AUTO_INCREMENT NOT NULL,
	`clientId` int,
	`eventType` enum('MEETING','ADJUSTMENT','ESTIMATE','INSPECTION','APPOINTMENT','DEADLINE','OTHER') NOT NULL,
	`title` varchar(200) NOT NULL,
	`description` text,
	`eventDate` timestamp NOT NULL,
	`eventTime` varchar(10),
	`endTime` varchar(10),
	`address` text,
	`adjusterNumber` varchar(100),
	`adjusterName` varchar(200),
	`adjusterPhone` varchar(20),
	`adjusterEmail` varchar(320),
	`insuranceCompany` varchar(200),
	`claimNumber` varchar(100),
	`status` enum('SCHEDULED','COMPLETED','CANCELLED','RESCHEDULED') NOT NULL DEFAULT 'SCHEDULED',
	`reminderSent` int DEFAULT 0,
	`notes` text,
	`createdBy` int NOT NULL,
	`updatedBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `events_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `tasks` (
	`id` int AUTO_INCREMENT NOT NULL,
	`clientId` int,
	`title` varchar(200) NOT NULL,
	`description` text,
	`category` enum('DOCUMENTACION','SEGUIMIENTO','ESTIMADO','REUNION','REVISION','OTRO') NOT NULL DEFAULT 'OTRO',
	`priority` enum('ALTA','MEDIA','BAJA') NOT NULL DEFAULT 'MEDIA',
	`status` enum('PENDIENTE','EN_PROGRESO','COMPLETADA','CANCELADA') NOT NULL DEFAULT 'PENDIENTE',
	`assignedTo` int,
	`dueDate` timestamp,
	`completedAt` timestamp,
	`attachments` text,
	`createdBy` int NOT NULL,
	`updatedBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `tasks_id` PRIMARY KEY(`id`)
);
