ALTER TABLE `documents`
  MODIFY `documentType` ENUM(
    'POLIZA','CONTRATO','FOTO','ESTIMADO','ESTIMADO_ASEGURANZA','ESTIMADO_NUESTRO','MATERIAL_ORDER','CREW_REPORT','FACTURA','PERMISO','OTRO'
  ) NOT NULL;