export const ENV = {
  cookieSecret: process.env.JWT_SECRET ?? "",
  cookieDomain: process.env.COOKIE_DOMAIN ?? "",
  publicAppUrl: process.env.PUBLIC_APP_URL ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  googleClientId: process.env.GOOGLE_CLIENT_ID ?? "",
  googleClientSecret: process.env.GOOGLE_CLIENT_SECRET ?? "",
  googleGmailClientId: process.env.GOOGLE_GMAIL_CLIENT_ID ?? "",
  googleGmailClientSecret: process.env.GOOGLE_GMAIL_CLIENT_SECRET ?? "",
  googleGmailTopic: process.env.GOOGLE_GMAIL_TOPIC ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  groqApiKey: process.env.GROQ_API_KEY ?? "",
  groqModel: process.env.GROQ_MODEL ?? "llama-3.1-70b-versatile",
  resendApiKey: process.env.RESEND_API_KEY ?? "",
  emailFrom: process.env.EMAIL_FROM ?? "",
  emailReplyTo: process.env.EMAIL_REPLY_TO ?? "",
  appBaseUrl: process.env.APP_BASE_URL ?? process.env.PUBLIC_APP_URL ?? "",
  inviteTokenHours: Number(process.env.INVITE_TOKEN_HOURS ?? 72),
  passwordResetTokenHours: Number(process.env.PASSWORD_RESET_TOKEN_HOURS ?? 2),
  stripeSecretKey: process.env.STRIPE_SECRET_KEY ?? "",
  stripeWebhookSecret: process.env.STRIPE_WEBHOOK_SECRET ?? "",
  stripePriceStarter: process.env.STRIPE_PRICE_STARTER ?? "",
  stripePriceProfessional: process.env.STRIPE_PRICE_PROFESSIONAL ?? "",
  stripePriceEnterprise: process.env.STRIPE_PRICE_ENTERPRISE ?? "",
  stripePriceExtraSeat: process.env.STRIPE_PRICE_EXTRA_SEAT ?? "",
  billingCompedCode: process.env.BILLING_COMPED_CODE ?? "",
};
