export const ENV = {
  // appId usa fallback "local-crm" para login sin OAuth
  appId: process.env.VITE_APP_ID ?? "local-crm-app",
  cookieSecret: process.env.JWT_SECRET ?? "",
  cookieDomain: process.env.COOKIE_DOMAIN ?? "",
  publicAppUrl: process.env.PUBLIC_APP_URL ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  googleClientId: process.env.GOOGLE_CLIENT_ID ?? "",
  googleClientSecret: process.env.GOOGLE_CLIENT_SECRET ?? "",
  googleGmailClientId: process.env.GOOGLE_GMAIL_CLIENT_ID ?? "",
  googleGmailClientSecret: process.env.GOOGLE_GMAIL_CLIENT_SECRET ?? "",
  googleGmailTopic: process.env.GOOGLE_GMAIL_TOPIC ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  resendApiKey: process.env.RESEND_API_KEY ?? "",
  emailFrom: process.env.EMAIL_FROM ?? "",
  appBaseUrl: process.env.APP_BASE_URL ?? process.env.PUBLIC_APP_URL ?? "",
  inviteTokenHours: Number(process.env.INVITE_TOKEN_HOURS ?? 72),
  passwordResetTokenHours: Number(process.env.PASSWORD_RESET_TOKEN_HOURS ?? 2),
  stripeSecretKey: process.env.STRIPE_SECRET_KEY ?? "",
  stripeWebhookSecret: process.env.STRIPE_WEBHOOK_SECRET ?? "",
  stripePriceStarter: process.env.STRIPE_PRICE_STARTER ?? "",
  stripePriceProfessional: process.env.STRIPE_PRICE_PROFESSIONAL ?? "",
  stripePriceEnterprise: process.env.STRIPE_PRICE_ENTERPRISE ?? "",
  stripePriceExtraSeat: process.env.STRIPE_PRICE_EXTRA_SEAT ?? "",
};
