import { PDFDocument, StandardFonts, rgb } from "pdf-lib";

type CrewReportInput = {
  organizationName: string;
  generatedBy: string;
  reportNumber: string;
  reportDate: string;
  clientName: string;
  projectName: string;
  propertyAddress?: string | null;
  roofType?: string | null;
  roofColor?: string | null;
  roofSquares?: number | null;
  scopeItems: string[];
  scopeOther?: string | null;
  materialItems?: Array<{ name: string; quantity: number; unit?: string | null; notes?: string | null }>;
  notes?: string | null;
};

export async function generateCrewReportPdf(input: CrewReportInput) {
  const pdfDoc = await PDFDocument.create();
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const bold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);
  let page = pdfDoc.addPage([612, 792]);
  const { width, height } = page.getSize();

  const margin = 36;
  let y = height - margin;

  const drawLine = (text: string, size = 12, isBold = false, color = rgb(0.1, 0.1, 0.1)) => {
    if (y < margin + 60) {
      page = pdfDoc.addPage([612, 792]);
      y = height - margin;
    }
    page.drawText(text, {
      x: margin,
      y,
      size,
      font: isBold ? bold : font,
      color,
    });
    y -= size + 6;
  };

  const wrapText = (text: string, maxWidth: number, size: number) => {
    const words = text.split(" ");
    const lines: string[] = [];
    let current = "";
    words.forEach((word) => {
      const next = current ? `${current} ${word}` : word;
      const width = font.widthOfTextAtSize(next, size);
      if (width <= maxWidth) {
        current = next;
      } else {
        if (current) lines.push(current);
        current = word;
      }
    });
    if (current) lines.push(current);
    return lines;
  };

  const drawSectionTitle = (title: string) => {
    y -= 6;
    page.drawRectangle({
      x: margin,
      y: y - 8,
      width: width - margin * 2,
      height: 22,
      color: rgb(0.94, 0.95, 0.97),
    });
    page.drawText(title, {
      x: margin + 8,
      y: y - 2,
      size: 11,
      font: bold,
      color: rgb(0.2, 0.2, 0.2),
    });
    y -= 22;
  };

  drawLine(input.organizationName, 14, true);
  drawLine("Crew Work Report", 16, true);
  drawLine("Construction Scope and Field Instructions", 10, false, rgb(0.4, 0.4, 0.4));
  y -= 6;

  const leftInfo = [
    `Report Number: ${input.reportNumber}`,
    `Date: ${input.reportDate}`,
    `Generated by: ${input.generatedBy}`,
  ];
  const rightInfo = [
    `Client: ${input.clientName}`,
    `Project: ${input.projectName}`,
    input.propertyAddress ? `Address: ${input.propertyAddress}` : "",
  ].filter(Boolean);

  leftInfo.forEach((line) => drawLine(line, 10));
  y += 6;
  const rightX = width / 2 + 10;
  rightInfo.forEach((line, index) => {
    page.drawText(line, {
      x: rightX,
      y: height - margin - 42 - index * 16,
      size: 10,
      font,
      color: rgb(0.2, 0.2, 0.2),
    });
  });
  y = height - margin - 42 - leftInfo.length * 16;

  drawSectionTitle("Project Summary");
  if (input.roofSquares) drawLine(`Roof squares: ${input.roofSquares}`, 10);
  if (input.roofType) drawLine(`Roof material: ${input.roofType}`, 10);
  if (input.roofColor) drawLine(`Roof color: ${input.roofColor}`, 10);

  drawSectionTitle("Scope of Work");
  const scopeList = [...input.scopeItems];
  if (input.scopeOther) scopeList.push(input.scopeOther);
  if (!scopeList.length) {
    drawLine("Scope not specified.", 10);
  } else {
    scopeList.forEach((scope) => drawLine(`- ${scope}`, 10));
  }

  if (input.materialItems && input.materialItems.length) {
    drawSectionTitle("Materials Summary");
    input.materialItems.slice(0, 12).forEach((item) => {
      const unit = item.unit ? ` ${item.unit}` : "";
      drawLine(`- ${item.name}: ${item.quantity}${unit}`, 10);
    });
  }

  drawSectionTitle("Crew Responsibilities");
  const responsibilityText = [
    "Protect all property, landscaping, and HVAC/AC units at all times.",
    "Crew is responsible for damage caused by lack of protection and it may affect final compensation.",
    "No work outside of this scope should be performed without supervisor approval.",
    "Report any hidden damage or unexpected conditions immediately.",
  ];
  responsibilityText.forEach((line) => drawLine(`- ${line}`, 10));

  if (input.notes) {
    drawSectionTitle("Field Notes");
    const lines = wrapText(input.notes, width - margin * 2 - 8, 10);
    lines.forEach((line) => drawLine(line, 10));
  }

  y = margin - 10;
  page.drawLine({
    start: { x: margin, y: y + 24 },
    end: { x: width - margin, y: y + 24 },
    thickness: 0.5,
    color: rgb(0.82, 0.82, 0.82),
  });
  page.drawText(`Generated by ${input.organizationName}`, {
    x: margin,
    y: y + 6,
    size: 8,
    font,
    color: rgb(0.5, 0.5, 0.5),
  });

  return await pdfDoc.save();
}
