import { PDFDocument, StandardFonts, rgb } from "pdf-lib";

type MaterialOrderItem = {
  name: string;
  quantity: number;
  unit?: string | null;
  notes?: string | null;
  required?: boolean | null;
};

type MaterialOrderPdfInput = {
  organizationName: string;
  generatedBy: string;
  orderNumber: string;
  orderDate: string;
  clientName: string;
  projectName: string;
  propertyAddress?: string | null;
  roofType?: string | null;
  roofColor?: string | null;
  roofSquares?: number | null;
  items: MaterialOrderItem[];
  notes?: string | null;
};

export async function generateMaterialOrderPdf(input: MaterialOrderPdfInput) {
  const pdfDoc = await PDFDocument.create();
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const bold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);
  let page = pdfDoc.addPage([612, 792]);
  const { width, height } = page.getSize();

  const margin = 36;
  let y = height - margin;

  const drawLine = (text: string, size = 12, isBold = false, color = rgb(0.1, 0.1, 0.1)) => {
    if (y < margin + 60) {
      page = pdfDoc.addPage([612, 792]);
      y = height - margin;
    }
    page.drawText(text, {
      x: margin,
      y,
      size,
      font: isBold ? bold : font,
      color,
    });
    y -= size + 6;
  };

  const drawSectionTitle = (title: string) => {
    y -= 6;
    page.drawRectangle({
      x: margin,
      y: y - 8,
      width: width - margin * 2,
      height: 22,
      color: rgb(0.94, 0.95, 0.97),
    });
    page.drawText(title, {
      x: margin + 8,
      y: y - 2,
      size: 11,
      font: bold,
      color: rgb(0.2, 0.2, 0.2),
    });
    y -= 22;
  };

  const wrapText = (text: string, maxWidth: number, size: number) => {
    const words = text.split(" ");
    const lines: string[] = [];
    let current = "";
    words.forEach((word) => {
      const next = current ? `${current} ${word}` : word;
      const width = font.widthOfTextAtSize(next, size);
      if (width <= maxWidth) {
        current = next;
      } else {
        if (current) lines.push(current);
        current = word;
      }
    });
    if (current) lines.push(current);
    return lines;
  };

  drawLine(input.organizationName, 14, true);
  drawLine("Material Order Sheet", 16, true);
  drawLine("Material Purchase Order", 10, false, rgb(0.4, 0.4, 0.4));
  y -= 6;

  const infoLeft = [
    `Order Number: ${input.orderNumber}`,
    `Date: ${input.orderDate}`,
    `Generated by: ${input.generatedBy}`,
  ];
  const infoRight = [
    `Client: ${input.clientName}`,
    `Project: ${input.projectName}`,
    input.propertyAddress ? `Address: ${input.propertyAddress}` : "",
  ].filter(Boolean);

  infoLeft.forEach((line) => drawLine(line, 10));
  y += 6;
  const rightX = width / 2 + 10;
  infoRight.forEach((line, index) => {
    page.drawText(line, {
      x: rightX,
      y: height - margin - 42 - index * 16,
      size: 10,
      font,
      color: rgb(0.2, 0.2, 0.2),
    });
  });
  y = height - margin - 42 - infoLeft.length * 16;

  if (input.roofType || input.roofSquares) {
    drawSectionTitle("Roof Summary");
    if (input.roofType) drawLine(`Roof material: ${input.roofType}`, 10);
    if (input.roofColor) drawLine(`Roof color: ${input.roofColor}`, 10);
    if (input.roofSquares) drawLine(`Roof squares: ${input.roofSquares}`, 10);
  }

  drawSectionTitle("Material List");

  const columns = [
    { title: "#", width: 24 },
    { title: "Material Description", width: 190 },
    { title: "Specification / Notes", width: 170 },
    { title: "Qty", width: 60 },
    { title: "Unit", width: 50 },
  ];
  const tableWidth = columns.reduce((sum, col) => sum + col.width, 0);
  const tableX = margin;

  const drawTableHeader = () => {
    page.drawRectangle({
      x: tableX,
      y: y - 18,
      width: tableWidth,
      height: 20,
      color: rgb(0.2, 0.25, 0.32),
    });
    let cursorX = tableX + 4;
    columns.forEach((col) => {
      page.drawText(col.title, {
        x: cursorX,
        y: y - 14,
        size: 9,
        font: bold,
        color: rgb(1, 1, 1),
      });
      cursorX += col.width;
    });
    y -= 24;
  };

  const drawRow = (index: number, item: MaterialOrderItem) => {
    const qty = Number.isFinite(item.quantity) ? item.quantity : 0;
    const unit = item.unit ?? "";
    const notes = item.notes ?? "";
    const materialLines = wrapText(item.name, columns[1].width - 8, 9);
    const notesLines = wrapText(notes, columns[2].width - 8, 9);
    const rowLines = Math.max(materialLines.length, notesLines.length, 1);
    const rowHeight = rowLines * 12 + 6;

    if (y < margin + rowHeight + 20) {
      page = pdfDoc.addPage([612, 792]);
      y = height - margin;
      drawTableHeader();
    }

    let cursorX = tableX + 4;
    const rowTop = y;

    page.drawText(String(index), { x: cursorX, y: rowTop - 10, size: 9, font });
    cursorX += columns[0].width;

    materialLines.forEach((line, lineIndex) => {
      page.drawText(line, { x: cursorX, y: rowTop - 10 - lineIndex * 12, size: 9, font });
    });
    cursorX += columns[1].width;

    notesLines.forEach((line, lineIndex) => {
      page.drawText(line, { x: cursorX, y: rowTop - 10 - lineIndex * 12, size: 9, font });
    });
    cursorX += columns[2].width;

    page.drawText(String(qty), { x: cursorX, y: rowTop - 10, size: 9, font });
    cursorX += columns[3].width;
    page.drawText(unit, { x: cursorX, y: rowTop - 10, size: 9, font });

    y -= rowHeight;
    page.drawLine({
      start: { x: tableX, y },
      end: { x: tableX + tableWidth, y },
      thickness: 0.5,
      color: rgb(0.85, 0.85, 0.85),
    });
  };

  drawTableHeader();
  input.items.forEach((item, index) => drawRow(index + 1, item));

  if (input.notes) {
    drawSectionTitle("Special Instructions");
    const lines = wrapText(input.notes, width - margin * 2 - 8, 10);
    lines.forEach((line) => drawLine(line, 10));
  }

  y = margin - 10;
  page.drawLine({
    start: { x: margin, y: y + 24 },
    end: { x: width - margin, y: y + 24 },
    thickness: 0.5,
    color: rgb(0.82, 0.82, 0.82),
  });
  page.drawText(`Generated by ${input.organizationName}`, {
    x: margin,
    y: y + 6,
    size: 8,
    font,
    color: rgb(0.5, 0.5, 0.5),
  });

  return await pdfDoc.save();
}
